# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install nuget tool'

- task: NuGetAuthenticate@1

- task: PowerShell@2
  displayName: 'Build Identity Server nuget packages'
  inputs:
    filePath: './build.ps1'

- task: PublishBuildArtifacts@1 

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: './nuget/**/*.nupkg;!./nuget/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '96863222-b952-4fd2-911c-dcc563bef63d'